name: CI

on: [push]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm ci
            - run: npm run lint
            - run: npm run tsc

    test:
        runs-on: ubuntu-latest

        needs: lint

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm ci
            - run: npm run test

    build:
        runs-on: ubuntu-latest

        needs: test

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 14
            - run: npm ci
            - run: npm run build
              env:
                  CI: true
            - uses: actions/upload-artifact@v1
              with:
                  name: build
                  path: dist
